version: 2
updates:
  - package-ecosystem: 'npm'
    target-branch: 'main'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      minor-and-patch-updates:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
